name: demo_database
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  sqflite_common_ffi_web: ^0.4.5+3
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/anhdaidien.jpg
    - images/hinhnenzalo.jpg

